-- MySQL Workbench Synchronization
-- Generated: 2020-06-09 16:06
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: familia sierra

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `TiendaMacota` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `TiendaMacota`.`SERVICIO` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `costo` VARCHAR(45) NOT NULL,
  `estado` ENUM('disponible', 'no disponible') NOT NULL,
  `TipoServicio` ENUM('Guarderia','Baño', 'Peluqueria') NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `TiendaMacota`.`CITA` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `horaInico` TIME NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `VENTA_Id` INT(11) NOT NULL,
  `PERSONA_Id` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_CITA_VENTA1_idx` (`VENTA_Id` ASC) VISIBLE,
  INDEX `fk_CITA_PERSONA1_idx` (`PERSONA_Id` ASC) VISIBLE,
  CONSTRAINT `fk_CITA_VENTA1`
    FOREIGN KEY (`VENTA_Id`)
    REFERENCES `TiendaMacota`.`VENTA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CITA_PERSONA1`
    FOREIGN KEY (`PERSONA_Id`)
    REFERENCES `TiendaMacota`.`PERSONA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `TiendaMacota`.`MASCOTA` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `genero` ENUM('hembra', 'macho', 'indefinido') NOT NULL,
  `RAZA_Id` INT(11) NOT NULL,
  `PERSONA_Id` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_MASCOTA_RAZA1_idx` (`RAZA_Id` ASC) VISIBLE,
  INDEX `fk_MASCOTA_PERSONA1_idx` (`PERSONA_Id` ASC) VISIBLE,
  CONSTRAINT `fk_MASCOTA_RAZA1`
    FOREIGN KEY (`RAZA_Id`)
    REFERENCES `TiendaMacota`.`RAZA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MASCOTA_PERSONA1`
    FOREIGN KEY (`PERSONA_Id`)
    REFERENCES `TiendaMacota`.`PERSONA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `TiendaMacota`.`PERSONA` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipoDocumento` ENUM('Cedula ciduadania', 'Tarjeta Identidad','otro') NOT NULL,
  `documento` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` BIGINT(20) NOT NULL,
  `telefonoOpcional` BIGINT(20) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(8) NULL DEFAULT NULL,
  `TIPOPERSONA` ENUM('administrador', 'proveedor', 'cliente') NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `documento_UNIQUE` (`documento` ASC) VISIBLE,
  UNIQUE INDEX `idPERSONA_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `TiendaMacota`.`VENTA` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(45) NULL DEFAULT NULL,
  `subTotal` VARCHAR(45) NULL DEFAULT NULL,
  `totalaPagar` VARCHAR(45) NOT NULL,
  `PERSONA_Id` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_VENTA_PERSONA1_idx` (`PERSONA_Id` ASC) VISIBLE,
  CONSTRAINT `fk_VENTA_PERSONA1`
    FOREIGN KEY (`PERSONA_Id`)
    REFERENCES `TiendaMacota`.`PERSONA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `TiendaMacota`.`ELEMENTO` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipoElemento` ENUM('medicamentos', 'accesorios', 'alimentos') NOT NULL,
  `tamaño` VARCHAR(45) NULL DEFAULT NULL,
  `material` VARCHAR(45) NULL DEFAULT NULL,
  `color` VARCHAR(45) NOT NULL,
  `marca` ENUM('Dog shaw', 'Chunky') NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `TiendaMacota`.`COLOR` (
  `idCOLOR` INT(11) NOT NULL,
  `nomCOLOR` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCOLOR`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `TiendaMacota`.`MARCA` (
  `idMARCA` INT(11) NOT NULL AUTO_INCREMENT,
  `nomMARCA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMARCA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `TiendaMacota`.`INVENTARIO` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` INT(11) NOT NULL,
  `precioCosto` DOUBLE NOT NULL,
  `precioVenta` DOUBLE NOT NULL,
  `MASCOTA_Id` INT(11) NOT NULL,
  `COMPRA_Id` INT(11) NOT NULL,
  `ELEMENTO_Id` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_INVENTARIO_MASCOTA1_idx` (`MASCOTA_Id` ASC) VISIBLE,
  INDEX `fk_INVENTARIO_COMPRA1_idx` (`COMPRA_Id` ASC) VISIBLE,
  INDEX `fk_INVENTARIO_ELEMENTO1_idx` (`ELEMENTO_Id` ASC) VISIBLE,
  CONSTRAINT `fk_INVENTARIO_MASCOTA1`
    FOREIGN KEY (`MASCOTA_Id`)
    REFERENCES `TiendaMacota`.`MASCOTA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INVENTARIO_COMPRA1`
    FOREIGN KEY (`COMPRA_Id`)
    REFERENCES `TiendaMacota`.`COMPRA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INVENTARIO_ELEMENTO1`
    FOREIGN KEY (`ELEMENTO_Id`)
    REFERENCES `TiendaMacota`.`ELEMENTO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `TiendaMacota`.`COMPRA` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaCompra` VARCHAR(45) NOT NULL,
  `total` DOUBLE NOT NULL,
  `PERSONA_Id` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_COMPRA_PERSONA1_idx` (`PERSONA_Id` ASC) VISIBLE,
  CONSTRAINT `fk_COMPRA_PERSONA1`
    FOREIGN KEY (`PERSONA_Id`)
    REFERENCES `TiendaMacota`.`PERSONA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `TiendaMacota`.`ARTICULOSVENTA` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` VARCHAR(45) NOT NULL,
  `INVENTARIO_Id` INT(11) NOT NULL,
  `VENTA_Id` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_ARTICULOSVENTA_INVENTARIO1_idx` (`INVENTARIO_Id` ASC) VISIBLE,
  INDEX `fk_ARTICULOSVENTA_VENTA1_idx` (`VENTA_Id` ASC) VISIBLE,
  CONSTRAINT `fk_ARTICULOSVENTA_INVENTARIO1`
    FOREIGN KEY (`INVENTARIO_Id`)
    REFERENCES `TiendaMacota`.`INVENTARIO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ARTICULOSVENTA_VENTA1`
    FOREIGN KEY (`VENTA_Id`)
    REFERENCES `TiendaMacota`.`VENTA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `TiendaMacota`.`table1` (
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `TiendaMacota`.`Descripcion` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `HoraInicio` TIME NOT NULL,
  `HoraFin` TIME NOT NULL,
  `habitosAlimenticios` VARCHAR(45) NOT NULL,
  `comportamientos` VARCHAR(45) NULL DEFAULT NULL,
  `notasSobreAnimal` VARCHAR(45) NULL DEFAULT NULL,
  `DescripcionServicio` VARCHAR(45) NULL DEFAULT NULL,
  `CITA_Id` INT(11) NOT NULL,
  `MASCOTA_Id` INT(11) NOT NULL,
  `SERVICIO_Id` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Descripcion_CITA1_idx` (`CITA_Id` ASC) VISIBLE,
  INDEX `fk_Descripcion_MASCOTA1_idx` (`MASCOTA_Id` ASC) VISIBLE,
  INDEX `fk_Descripcion_SERVICIO1_idx` (`SERVICIO_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Descripcion_CITA1`
    FOREIGN KEY (`CITA_Id`)
    REFERENCES `TiendaMacota`.`CITA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Descripcion_MASCOTA1`
    FOREIGN KEY (`MASCOTA_Id`)
    REFERENCES `TiendaMacota`.`MASCOTA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Descripcion_SERVICIO1`
    FOREIGN KEY (`SERVICIO_Id`)
    REFERENCES `TiendaMacota`.`SERVICIO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `TiendaMacota`.`RAZA` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `especie` ENUM('Acuatico','Canino','Felino','Avicola','Roedor') NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
