-- MySQL Script generated by MySQL Workbench
-- Thu Jul  9 11:29:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`persona` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipoDocumento` ENUM('C.C', 'T.I', 'Otro') NOT NULL,
  `documento` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` BIGINT(20) NOT NULL,
  `telefonoOpcional` BIGINT(20) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NULL DEFAULT NULL,
  `TIPOPERSONA` ENUM('Admin', 'Cliente', 'Proveedor') NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`compra` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `total` DOUBLE NOT NULL,
  `PERSONA_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_COMPRA_PERSONA1` (`PERSONA_id` ASC) ,
  CONSTRAINT `fk_COMPRA_PERSONA1`
    FOREIGN KEY (`PERSONA_id`)
    REFERENCES `proyecto`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`elemento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`elemento` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipoElemento` ENUM('Accesorios', 'Medicamentos', 'Alimentos') NOT NULL,
  `tamaño` VARCHAR(45) NULL DEFAULT NULL,
  `material` VARCHAR(45) NULL DEFAULT NULL,
  `color` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`raza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`raza` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `especie` ENUM('Acuatico', 'Canino', 'Felino', 'Avicola', 'Roedor') NOT NULL,
  `estado` ENUM('Disponible', 'No Disponible') NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`mascota` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `genero` ENUM('Macho', 'Hembra') NOT NULL,
  `RAZA_id` INT(10) UNSIGNED NOT NULL,
  `PERSONA_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_MASCOTA_RAZA` (`RAZA_id` ASC) ,
  INDEX `fk_MASCOTA_PERSONA1` (`PERSONA_id` ASC) ,
  CONSTRAINT `fk_MASCOTA_PERSONA1`
    FOREIGN KEY (`PERSONA_id`)
    REFERENCES `proyecto`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MASCOTA_RAZA`
    FOREIGN KEY (`RAZA_id`)
    REFERENCES `proyecto`.`raza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`inventario` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cantidad` INT(11) NOT NULL,
  `precioCosto` DOUBLE NOT NULL,
  `precioVenta` DOUBLE NOT NULL,
  `COMPRA_id` INT(10) UNSIGNED NOT NULL,
  `MASCOTA_id` INT(10) UNSIGNED NOT NULL,
  `ELEMENTO_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_INVENTARIO_COMPRA1` (`COMPRA_id` ASC) ,
  INDEX `fk_INVENTARIO_MASCOTA1` (`MASCOTA_id` ASC) ,
  INDEX `fk_INVENTARIO_ELEMENTO1` (`ELEMENTO_id` ASC) ,
  CONSTRAINT `fk_INVENTARIO_COMPRA1`
    FOREIGN KEY (`COMPRA_id`)
    REFERENCES `proyecto`.`compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INVENTARIO_ELEMENTO1`
    FOREIGN KEY (`ELEMENTO_id`)
    REFERENCES `proyecto`.`elemento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INVENTARIO_MASCOTA1`
    FOREIGN KEY (`MASCOTA_id`)
    REFERENCES `proyecto`.`mascota` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`venta` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `subtotal` DOUBLE NULL DEFAULT NULL,
  `totalApagar` DOUBLE NOT NULL,
  `PERSONA_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_VENTA_PERSONA1` (`PERSONA_id` ASC) ,
  CONSTRAINT `fk_VENTA_PERSONA1`
    FOREIGN KEY (`PERSONA_id`)
    REFERENCES `proyecto`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`articulosventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`articulosventa` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cantidad` INT(11) NOT NULL,
  `INVENTARIO_id` INT(10) UNSIGNED NOT NULL,
  `VENTA_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ARTICULOSVENTA_INVENTARIO1` (`INVENTARIO_id` ASC) ,
  INDEX `fk_ARTICULOSVENTA_VENTA1` (`VENTA_id` ASC) ,
  CONSTRAINT `fk_ARTICULOSVENTA_INVENTARIO1`
    FOREIGN KEY (`INVENTARIO_id`)
    REFERENCES `proyecto`.`inventario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ARTICULOSVENTA_VENTA1`
    FOREIGN KEY (`VENTA_id`)
    REFERENCES `proyecto`.`venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`cita` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `horaInicio` TIME NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `PERSONA_id` INT(10) UNSIGNED NOT NULL,
  `VENTA_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CITA_PERSONA1` (`PERSONA_id` ASC) ,
  INDEX `fk_CITA_VENTA1` (`VENTA_id` ASC) ,
  CONSTRAINT `fk_CITA_PERSONA1`
    FOREIGN KEY (`PERSONA_id`)
    REFERENCES `proyecto`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CITA_VENTA1`
    FOREIGN KEY (`VENTA_id`)
    REFERENCES `proyecto`.`venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`servicio` (
  `id` INT(10) UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `costo` VARCHAR(45) NOT NULL,
  `estado` ENUM('Disponible', 'No Disponible') NOT NULL,
  `tipoServicio` ENUM('Guarderia', 'Peluqueria', 'Baño') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`descripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`descripcion` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  `habitosAlimenticios` VARCHAR(45) NULL DEFAULT NULL,
  `comportamientos` VARCHAR(45) NULL DEFAULT NULL,
  `notasSobreAnimal` VARCHAR(45) NULL DEFAULT NULL,
  `descripcionServicio` VARCHAR(45) NULL DEFAULT NULL,
  `SERVICIO_id` INT(10) UNSIGNED NOT NULL,
  `CITA_id` INT(10) UNSIGNED NOT NULL,
  `MASCOTA_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_DESCRIPCION_SERVICIO1` (`SERVICIO_id` ASC) ,
  INDEX `fk_DESCRIPCION_CITA1` (`CITA_id` ASC) ,
  INDEX `fk_DESCRIPCION_MASCOTA1` (`MASCOTA_id` ASC) ,
  CONSTRAINT `fk_DESCRIPCION_CITA1`
    FOREIGN KEY (`CITA_id`)
    REFERENCES `proyecto`.`cita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DESCRIPCION_MASCOTA1`
    FOREIGN KEY (`MASCOTA_id`)
    REFERENCES `proyecto`.`mascota` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DESCRIPCION_SERVICIO1`
    FOREIGN KEY (`SERVICIO_id`)
    REFERENCES `proyecto`.`servicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
